version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: ./script/container_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./script/container_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: ./script/validate.sh
      timeout: 120
      runas: root