version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: ./scripts/container_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/container_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: ./scripts/validate.sh
      timeout: 120
      runas: root
